### ISSUE TITLE
grafana 버전 업그레이드

### ISSUE THREAD

**Issue by jhgoh** [cpnr/computing#67]
grafana version을 업데이트함.

`grafana.yaml` 파일에서 

```
      containers:
        - name: grafana
          image: grafana/grafana:11.5.2
          imagePullPolicy: IfNotPresent
```

로 수정한 후

```
kubectl apply -f grafana.yaml
```

적용함. 잘 동작하는 것으로 보임.
